version: '3.8'

services:
  spark-notebook:
    image: jupyter/pyspark-notebook:latest
    container_name: pyspark-notebook
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    user: root
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
